[2023-09-06T21:02:33.286-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: streamings-dag.twitter_crawler manual__2023-09-07T00:02:31.054567+00:00 [queued]>
[2023-09-06T21:02:33.292-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: streamings-dag.twitter_crawler manual__2023-09-07T00:02:31.054567+00:00 [queued]>
[2023-09-06T21:02:33.292-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-09-06T21:02:33.322-0300] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): twitter_crawler> on 2023-09-07 00:02:31.054567+00:00
[2023-09-06T21:02:33.324-0300] {standard_task_runner.py:57} INFO - Started process 8974 to run task
[2023-09-06T21:02:33.327-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'streamings-dag', 'twitter_crawler', 'manual__2023-09-07T00:02:31.054567+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/streamings-dag.py', '--cfg-path', '/tmp/tmp1crf3ll0']
[2023-09-06T21:02:33.328-0300] {standard_task_runner.py:85} INFO - Job 10: Subtask twitter_crawler
[2023-09-06T21:02:33.366-0300] {task_command.py:415} INFO - Running <TaskInstance: streamings-dag.twitter_crawler manual__2023-09-07T00:02:31.054567+00:00 [running]> on host dany.
[2023-09-06T21:02:33.435-0300] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='danielbcuadros@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='streamings-dag' AIRFLOW_CTX_TASK_ID='twitter_crawler' AIRFLOW_CTX_EXECUTION_DATE='2023-09-07T00:02:31.054567+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-07T00:02:31.054567+00:00'
[2023-09-06T21:02:33.435-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-06T21:02:33.436-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/dany/airflow/dags/../../Streaming-insights/venv/bin/python /home/dany/airflow/dags/../../Streaming-insights/etls/twitter-crawler.py']
[2023-09-06T21:02:33.440-0300] {subprocess.py:86} INFO - Output:
[2023-09-06T21:03:48.765-0300] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-09-06T21:03:48.768-0300] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 8974. PIDs of all processes in the group: [8975, 8974]
[2023-09-06T21:03:48.768-0300] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 8974
[2023-09-06T21:03:48.768-0300] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-09-06T21:03:48.768-0300] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-09-06T21:03:48.821-0300] {process_utils.py:79} INFO - Process psutil.Process(pid=8974, status='terminated', exitcode=0, started='21:02:32') (8974) terminated with exit code 0
[2023-09-06T21:03:48.821-0300] {process_utils.py:79} INFO - Process psutil.Process(pid=8975, status='terminated', started='21:02:32') (8975) terminated with exit code None
